[%
    T = {
        configure_1                                = "IntranetUserJS: Remove excess spaces Configuration",
        configure_2                                = "Home",
        configure_3                                = "Plugins",
        configure_4                                = "&rsaquo; IntranetUserJS: Remove excess spaces &rsaquo; Configuration",
        configure_5                                = "ID of the report to use:",
        configure_6                                = "Save configuration",
        configure_7                                = "Upgrade status",
        configure_8                                = "Plugin has never been upgraded.",
        viewjs_1                                   = "IntranetUserJS: Remove excess spaces",
        viewjs_2                                   = "&rsaquo; RemoveExcessSpaces &rsaquo; View JS Tool",
    }
%]