[%
    T = {
        configure_1                                = "IntranetUserJS: Remove excess spaces -asetukset",
        configure_2                                = "Etusivu",
        configure_3                                = "Liitännäiset",
        configure_4                                = "&rsaquo; IntranetUserJS: Remove excess spaces &rsaquo; Asetukset",
        configure_5                                = "Käytettävän raportin ID:",
        configure_6                                = "Tallenna asetukset",
        configure_7                                = "Päivityksen tila",
        configure_8                                = "Liitännäistä ei ole koskaan päivitetty.",
        viewjs_1                                   = "IntranetUserJS: Remove excess spaces",
        viewjs_2                                   = "&rsaquo; RemoveExcessSpaces &rsaquo; Näytä JS-työkalu",
    }
%]