[%
    T = {
        configure_1                                = "IntranetUserJS: Ta bort överflödiga mellanslag-inställningar",
        configure_2                                = "Hem",
        configure_3                                = "Plugins",
        configure_4                                = "&rsaquo; IntranetUserJS: Ta bort överflödiga mellanslag &rsaquo; Inställningar",
        configure_5                                = "ID för rapporten som ska användas:",
        configure_6                                = "Spara inställningar",
        configure_7                                = "Uppgraderingsstatus",
        configure_8                                = "Pluginet har aldrig uppgraderats.",
        viewjs_1                                   = "IntranetUserJS: Ta bort överflödiga mellanslag",
        viewjs_2                                   = "&rsaquo; RemoveExcessSpaces &rsaquo; Visa JS-verktyg",
    }
%]